server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Sebas1005911567+
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

## cada vez que ponga a correr los servicios primero tengo que poner  a correr desde docker desktop: zipkin y redis

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


