server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                ## descarga desde ubuntu: docker run --name latestredis -d -p6379:6379 redis

##esto se configura con los mismos datos que hay desde la cuenta en el sitio web de okta
okta:
  oauth2:
    ##esto es desde API y luego default
    issuer: https://dev-18890427.okta.com/oauth2/default
    audience: api://default
    ##esto es desde Aplications y luego en microservices
    client-id: 0oa99dzgs8pesUvqP5d7
    client-secret: YcZrF2t6jzfBHeolVDRNVeyQW7B_9PvK6ZRNQw7N
    ##esto es desde API, luego default y despues scopes
    scopes: openid, email, profile, offline_access
